// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { RealSeqLetter } from '../../delphy/api/real-seq-letter.js';


export class Missation {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Missation {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

nodeIdx():number {
  return this.bb!.readInt32(this.bb_pos);
}

site():number {
  return this.bb!.readInt32(this.bb_pos + 4);
}

from():RealSeqLetter {
  return this.bb!.readUint8(this.bb_pos + 8);
}

static sizeOf():number {
  return 12;
}

static createMissation(builder:flatbuffers.Builder, node_idx: number, site: number, from: RealSeqLetter):flatbuffers.Offset {
  builder.prep(4, 12);
  builder.pad(3);
  builder.writeInt8(from);
  builder.writeInt32(site);
  builder.writeInt32(node_idx);
  return builder.offset();
}

}
