// Generate a random sample from a Gaussian distribution with mean `mu` and
// standard deviation `sigma`.
//
// Uses a simple Box-Muller implementation.  If we ever need more powerful random samplers
// in delphy-web, consider replacing this with a call to a robust library.
//
// Adapts a snippet generated by mistral.ai, which probably copied it from a random blog post,
// but I've verified it's correct.
//
export const randomGaussian = (mu: number, sigma: number) : number => {
  let u = 0, v = 0;
  while (u === 0) u = Math.random(); // Avoid log(0)
  while (v === 0) v = Math.random();
  const z = Math.sqrt(-2.0 * Math.log(u)) * Math.cos(2.0 * Math.PI * v);
  return mu + z * sigma;
}
